name: release

on:
  push:
    tags:
      - 'v*.*.*'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: package
        run: make build

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            concise-cli-linux-amd64
            concise-cli-windows-amd64.exe
            concise-cli-darwin-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}