name: Lint
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: lint module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
